# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_coupon_couponrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='beli',
            field=models.IntegerField(default=100),
        ),
    ]
